var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                         o                                           xxx        ",
   "                                                   xx               xx!xx       ",
   "                        xxx      o o      xx                        x!!!x       ",
   "                                                                    xx!xx       ",
   "                                xxxxx                                xvx        ",
   "                                                                            xx  ",
   "  xx                                     o o                                 x  ",
   "  x                     o                                                    x  ",
   "  x                                     xxxxx                             o  x  ",
   "  x        x  !!!  x    o                                                    x  ",
   "  x  @      x!!!!!x                               x  !!!xxx!!!  x            x  ",
   "  xxxxxxxxxxx!x!x!xxxxxxxxxxxxxx     xxxxxxxxxxxxxxx!!!!!x!!!!!xxxxxxxxxxxxxxx  ",
   "            x!!!!!x             x   x              x!x!x!x!x!x!x      x         ",
   "           x  ! !  x            x!!!x              x!!!!!x!!!!!x                ",
   "                              x !!!!! x           x  ! !   ! !  x               ",
   "                               x!x!x!x                                          ",
   "                               x!!!!!x                                          ",
   "                              x  ! !  x                                         ",
   "                                                                                "],
  ["                                                                                                                 ",
   "                                             xxxxx                                                               ",
   "                                            xx!!!xx                                                              ",
   "                                            x!!!!!x                                                              ",
   "                                            x!x!x!x                                                              ",
   "                                            x!!!!!x               o   o                                          ",
   "                                              ! !               xxxxxxxx                                         ",
   "                                              xvx               x                                                ",
   "                                                               xx                                                ",
   "                                                            xxxxx                                                ",
   "                                                                           xx                                    ",
   "                                                   xxxx                   xxxx                                   ",
   "                                             xx    x  x                  xxxxxx                                  ",
   "                                             x     x  xx                xxxxxxxx                                 ",
   "                                             x     x                   xxxxxxxxxx                             x  ",
   "                                             x    xx                  xxxxxxxxxxxx                            x  ",
   "                                             x     x     o  o                                                ox  ",
   "                x   x   !!!                  x     x                                                   xxxxxxxx  ",
   "               xx   xx !!!!!                 xx         xxxxxx                                         x         ",
   "              xx     xx!x!x!xxx o x                          xxx       xx                        xxxxxxxx        ",
   "      @       x     oxx!!!!!xxx   xx                                  xxxx                      xx               ",
   "     xxx     xx    xxxx ! ! xxx   xxx                                xxxxxx                    xxx               ",
   "     x x     xx   !  xx !!! xxx o xxxx           xxxx               xxxxxxxx                  xxxx               ",
   " !!! x x !!! xx x!   xx!!!!!xx    xxxxx            xx              xxxxxxxxxx              o xxxxx               ",
   "!!!!!x x!!!!!xx      xx!x!x!xx    xxxxxx    xx    =xx=     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "!x!x!x x!x!x!xxo     xx!!!!!xx    o        xxx!!!!!xx!!!!!!xx                                                    ",
   "!!!!!x x!!!!!xxxx    xx ! ! xx            xxxx!!!!!xx!!!!!!xx                                                    ",
   " ! ! x x ! ! xx  !                       xxxxx!!!!!xx!!!!!!xx                                                    ",
   " !!! x x !!! xx   !                     xxxxxx!!!!!!!!!!!!!xx                                                    ",
   "!!!!!x x!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                    "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "      x        x    x    x   x   x   x   xxxxx   xxxx                                                         ",
   "       x  xx  x     x    x x x   x x x   xxx     x xx                                                         ",
   "        x   x       x    x   x   x   x   xxxxx   x  x                                                         ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
